id: xfce4-settings
version: 4.20.0
about: collection of programs to adjust xfce preferences

configure: >-
  --enable-sound-settings
  --enable-pluggable-dialogs

post-script: |-
  install -vDm 0644 /dev/stdin %{install-root}/%{sysconfdir}/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml << "EOF"
  <?xml version="1.0" encoding="UTF-8"?>
  <channel name="xsettings" version="1.0">
    <property name="Net" type="empty">
      <property name="ThemeName" type="string" value="Orchis-Light"/>
      <property name="IconThemeName" type="string" value="Tela-light"/>
      <property name="DoubleClickTime" type="int" value="400"/>
      <property name="DoubleClickDistance" type="int" value="5"/>
      <property name="DndDragThreshold" type="int" value="8"/>
      <property name="CursorBlink" type="bool" value="true"/>
      <property name="CursorBlinkTime" type="int" value="1200"/>
      <property name="SoundThemeName" type="string" value="default"/>
      <property name="EnableEventSounds" type="bool" value="false"/>
      <property name="EnableInputFeedbackSounds" type="bool" value="false"/>
    </property>
    <property name="Xft" type="empty">
      <property name="DPI" type="int" value="110"/>
      <property name="Antialias" type="int" value="1"/>
      <property name="Hinting" type="int" value="-1"/>
      <property name="HintStyle" type="string" value="hintfull"/>
      <property name="RGBA" type="string" value="none"/>
      <!-- <property name="Lcdfilter" type="string" value="none"/> -->
    </property>
    <property name="Gtk" type="empty">
      <property name="CanChangeAccels" type="bool" value="false"/>
      <property name="ColorPalette" type="string" value="black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"/>
      <property name="FontName" type="string" value="IBM Plex Sans Regular 10"/>
      <property name="MonospaceFontName" type="string" value="Fira Code Regular 10"/>
      <property name="IconSizes" type="string" value=""/>
      <property name="KeyThemeName" type="string" value=""/>
      <property name="ToolbarStyle" type="string" value="icons"/>
      <property name="ToolbarIconSize" type="int" value="3"/>
      <property name="MenuImages" type="bool" value="true"/>
      <property name="ButtonImages" type="bool" value="true"/>
      <property name="MenuBarAccel" type="string" value="F10"/>
      <property name="CursorThemeName" type="string" value="Default"/>
      <property name="CursorThemeSize" type="int" value="0"/>
      <property name="DecorationLayout" type="string" value="menu:minimize,maximize,close"/>
      <property name="DialogsUseHeader" type="bool" value="false"/>
      <property name="TitlebarMiddleClick" type="string" value="lower"/>
    </property>
    <property name="Gdk" type="empty">
      <property name="WindowScalingFactor" type="int" value="1"/>
    </property>
    <property name="Xfce" type="empty">
      <property name="SyncThemes" type="bool" value="true"/>
    </property>
  </channel>
  EOF

depends:
  - components/xfce4/exo.yml
  - components/xfce4/garcon.yml
  - components/xfce4/xfconf.yml
  - components/libcanberra.yml
  - components/libnotify.yml
  - components/x11/libxklavier.yml
  - components/colord.yml
  - components/libinput.yml
  - components/upower.yml
  - components/xiccd.yml
  - components/x11/xf86-input-libinput.yml

build-depends:
  - components/intltool.yml
  
sources:
  - https://archive.xfce.org/src/xfce/xfce4-settings/%{version:2}/xfce4-settings-%{version}.tar.bz2
