#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH=${HERE}/usr/bin:${PATH}
export LD_LIBRARY_PATH=${HERE}/usr/lib:${LD_LIBRARY_PATH}
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"

exec peek ${@}