#!/bin/sh

UPTIME="$(uptime -p | sed -e 's/up //g')"
HOSTNAME="$(hostname)"

SHUTDOWN='⏻'
REBOOT=''
SUSPEND='󰒲'
LOCK=''
LOGOUT='󰍃'

YES=''
NO='󰜺'

ConfirmCommand() {
  rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
  		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
  		-theme-str 'listview {columns: 2; lines: 1;}' \
  		-theme-str 'element-text {horizontal-align: 0.5;}' \
  		-theme-str 'textbox {horizontal-align: 0.5;}' \
  		-dmenu \
  		-p 'Confirmation' \
  		-mesg 'Are you Sure?' \
  		-theme Powermenu
}

Confirm() {
  local _selected="$(echo -e "$YES\n$NO" | ConfirmCommand)"
  if [ $_selected = "$YES" ] ; then
    $@
  fi
}

SELECTED="$(echo -e "$LOGOUT\n$SUSPEND\n$LOCK\n$REBOOT\n$SHUTDOWN" | rofi -dmenu -p "Uptime: $UPTIME" -mesg "Uptime: $UPTIME" -theme Powermenu)"
case $SELECTED in
  $SHUTDOWN)  Confirm systemctl poweroff ;;
  $REBOOT)    Confirm systemctl reboot   ;;
  $SUSPEND)   Confirm systemctl suspend  ;;
  $LOGOUT)    Confirm swaymsg exit       ;;
  $LOCK)      swaylock                   ;;
esac