environ:
  - CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu
  - ARCH=x86_64

variables:
  arch: x86_64
  triplet: x86_64-linux-gnu

merge:
  - tools/compiler.yml
  - tools/environ.yml
  - tools/strip.yml
  - tools/variables.yml
