environ:
  - CFLAGS=-march=arm64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - CXXFLAGS=-march=arm64 -mtune=generic -O2 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4
  - LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu
  - ARCH=arm64

variables:
  arch: arm64
  triplet: aarch64-linux-gnu

merge:
  - include/compiler.yml
  - include/environ.yml
  - include/strip.yml
  - include/variables.yml
