id: libconfig
version: 1.7.3
about: C/C++ configuration file library
sources:
  - libconfig-%{version}.tar.gz::https://github.com/hyperrealm/libconfig/archive/v%{version}.tar.gz

build-depends:
  - components/texinfo.yml

pre-script: autoreconf -fiv

build-type: autotools
