id: nvidia-settings
merge: [external/include/nvidia.inc]
about: Tool for configuring the NVIDIA graphics driver

depends:
  - components/gtk.yml
  - components/jansson.yml
  - components/libvdpau.yml
  - components/x11/libxv.yml
  - components/nvidia.yml
build-depends:
  - components/inetutils.yml
  - components/jansson.yml
  - components/libvdpau.yml
  - components/x11/libxext.yml
sources:
  - nvidia-settings-%{version}.tar.gz::https://github.com/NVIDIA/nvidia-settings/archive/%{version}.tar.gz
script: |-
  # patch -p0 < /files/libxnvctrl_so.patch
  make PREFIX=%{prefix}
  make -C src/libXNVCtrl PREFIX=%{prefix}
  make DESTDIR=%{install-root} PREFIX=%{prefix} install

  install -D -m644 doc/nvidia-settings.desktop "%{install-root}%{datadir}/applications/nvidia-settings.desktop"
  install -D -m644 doc/nvidia-settings.png "%{install-root}%{datadir}/pixmaps/nvidia-settings.png"
  sed \
    -e 's:__UTILS_PATH__:/usr/bin:' \
    -e 's:__PIXMAP_PATH__:%{datadir}/pixmaps:' \
    -e 's/__NVIDIA_SETTINGS_DESKTOP_CATEGORIES__/Settings;HardwareSettings;/' \
    -e 's/Icon=.*/Icon=nvidia-settings/' \
    -i "%{install-root}%{datadir}/applications/nvidia-settings.desktop"

  cd src/libXNVCtrl
  install -Dm 644 ./*.h -t "%{install-root}/usr/include/NVCtrl"
  install -d "%{install-root}/usr/lib"
  cp -Pr _out/Linux_x86_64/libXNVCtrl.* -t "%{install-root}/usr/lib"
