#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH=${HERE}/usr/bin:${PATH}
export LD_LIBRARY_PATH=${HERE}/usr/lib:${LD_LIBRARY_PATH}
SCRCPY_SERVER_PATH=${HERE}/usr/share/scrcpy/scrcpy-server
exec ${HERE}/usr/bin/scrcpy