#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export SOURCE_PATH=${HERE}/usr/lib/Source:${HERE}/usr/lib:${SOURCE_PATH}
export LD_LIBRARY_PATH=${HERE}/usr/lib:${LD_LIBRARY_PATH}
exec ${HERE}/usr/bin/Source "${@}"