#!/bin/sh
COMMAND=$1

if [ -z "$COMMAND" ] ; then
  echo "Usage: $0 <on/off>"
  echo "on or off tablet mode"
  exit 0
fi

start_service() {
  local _bin=$1
  shift

  local _pid=$(pidof $_bin)
  if [ -z "$_pid" ] ; then
    echo "Starting $_bin"
    $_bin $@ &
  fi
}

stop_service() {
  echo "Stopping $1"
  killall $1
}

enable_tablet_mode() {
  start_service iio-sway
  start_service wvkbd-mobintl -alpha 70 -L 300 &
}

disable_tablet_mode() {
  stop_service iio-sway
  stop_service wvkbd-mobintl
}

case "$COMMAND" in
  "on"|"ON")
    enable_tablet_mode
    ;;
  "off"|"OFF")
    disable_tablet_mode
    ;;
esac