#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export LD_LIBRARY_PATH=${HERE}/usr/lib:${LD_LIBRARY_PATH}
export PATH=${HERE}/usr/bin:${PATH}
export GSETTINGS_SCHEMA_DIR=${HERE}/usr/share/glib-2.0/schemas/:${GSETTINGS_SCHEMA_DIR}

exec ${HERE}/usr/bin/file-roller $@