id: xkeyboard-config
version: 2.42
about: Keyboard configuration database for the X Window System
sources:
  - https://xorg.freedesktop.org/archive/individual/data/%{id}/%{id}-%{version}.tar.xz

depends:
  - components/x11/xkbcomp.yml

build-depends:
  - components/libxslt.yml
  - components/meson.yml
  - components/python.yml
