command = "sway"
outputMode = "all"
scale = 1

[background]
red = 0.933
green = 0.945
blue = 1.0
opacity = 0.9

[headline]
red = 0.204
green = 0.298
blue = 0.392
opacity = 1.0

[prompt]
red = 0.204
green = 0.298
blue = 0.392
opacity = 1.0

[promptErr]
red = 0.988
green = 0.349
blue = 0.318
opacity = 1.0

[border]
red = 0.694
green = 0.698
blue = 1.0
opacity = 0.0