#!/bin/sh

# generate ca cache
make-ca -C /etc/ssl/certdata.txt

echo 'LANG=en_IN.UTF-8' > /etc/locale.conf
ln -sfv /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# install inspector globally
systemctl enable pkgupd-watchdog --global
# create Applications directory for pkgupd-watchdog
[[ ! -d /etc/skel/Applications ]] && mkdir -p /etc/skel/Applications