#!/bin/sh

# generating supported locals
mkdir -p /usr/lib/locale/
localedef -i en_IN -f UTF-8 en_IN.UTF-8
localedef -i en_US -f UTF-8 en_US.UTF-8

echo 'LANG=en_IN.UTF-8' > /etc/locale.conf
ln -sfv /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
