#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export DIA_BASE_PATH=${HERE}
export DIA_LIB_PATH=${HERE}/usr/lib/dia:${HERE}
export DIA_SHARE_PATH=${HERE}/data/shapes
export DIA_XSLT_PATH=${HERE}/data/xslt
export DIA_PYTHON_PATH=${HERE}/data/python:${HERE}/data
export DIA_SHEET_PATH=${HERE}/data/sheets
export LD_LIBRARY_PATH=${HERE}/usr/lib/dia:${LD_LIBRARY_PATH}
exec ${HERE}/usr/bin/dia $@