id: pkg-config
version: 0.29.2
about: |
  Tool for passing the include path and/or library paths to build tools during the configure and make phases of package installations

sources:
  - https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz

depends:
  runtime:
    - glibc
    
packages:
  - id: pkg
    dir: pkg-config-0.29.2
    flags:
      - id: configure
        value: >
          --with-internal-glib
          --disable-host-tool
          