#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH=${HERE}/usr/bin:${PATH}
export PYTHONPATH=${HERE}/python_modules:${HERE}/usr/lib/python3.9/site-packages:${PYTHONPATH}
exec ${HERE}/usr/bin/tuxemon