#!/bin/sh

# generate ca cache
make-ca -C /etc/ssl/certdata.txt

# PKGUPD fix
mkdir -p /var/cache/pkgupd/pkgs

echo 'LANG=en_IN.UTF-8' > /etc/locale.conf
ln -sfv /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# install inspector globally
systemctl enable inspector --global