id: system-config-printer
version: 1.5.18
about: A CUPS printer configuration tool and status applet

build-type: autotools

configure: >-
  --with-systemdsystemunitdir=%{libdir}/systemd/system
  --with-udevdir=%{libdir}/udev
  --with-udev-rules
  --with-cups-serverbin-dir=%{libdir}/cups

post-script: |-
  find %{install-root} -name "*.py" -exec python -mpy_compile {} +
  find %{install-root} -name "*.py" -exec python -O -mpy_compile {} +

  install -dm755 %{install-root}/usr/share/dbus-1/system.d
  mv %{install-root}/etc/dbus-1/system.d/* %{install-root}/usr/share/dbus-1/system.d
  rm -rf %{install-root}/etc/dbus-1

  # TODO: Why we need to do this manually??
  mv %{install-root}/%{libdir}/python3.11/site-packages/cupshelpers-1.0-py3.11.egg/cupshelpers \
     %{install-root}/%{libdir}/python3.11/site-packages/


depends:
- components/gtk.yml
- components/libnotify.yml
- components/libusb.yml
- components/libsecret.yml
- components/py/py-cairo.yml
- components/py/py-dbus.yml
- components/py/py-cups.yml
- components/py/py-curl.yml

sources:
- https://github.com/OpenPrinting/system-config-printer/releases/download/v%{version}/system-config-printer-%{version}.tar.xz
