id: kde-gtk-config
version: 5.27.7.1
about: Plasma kde-gtk-config

configure: >-
  -DCMAKE_BUILD_TYPE=Release
  -DBUILD_TESTING=OFF
  -Wno-dev

depends:
  - components/kconfigwidgets.yml
  - components/kdbusaddons.yml
  - components/plasma/kdecoration.yml
  - components/gtk.yml
  - components/gsettings-desktop-schemas.yml
build-depends:
  - components/extra-cmake-modules.yml
  - components/sassc.yml
sources:
  - https://download.kde.org/stable/plasma/%{version}/%{id}-%{version}.tar.xz
