id: x11-config
version: 0.0.1
about: X11 configurations

script: |-
  install -v -D -m 0644 /dev/stdin %{install-root}/%{datadir}/X11/xorg.conf.d/90-touchpad.conf << "EOF"
  Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
  EndSection
  EOF

build-depends:
  - components/bash.yml