set(CMAKE_C_COMPILE x86_64-rlxos-linux-gnu-gcc)
set(CMAKE_CXX_COMPILE x86_64-rlxos-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)