#!/bin/sh
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
if [[ -f ${XDG_CONFIG_HOME}/chrome-flags.conf ]] ; then
    CHROME_USER_FLAGS="$(cat ${XDG_CONFIG_HOME}/chrome-flags.conf)"
fi

exec ${HERE}/opt/google/chrome/google-chrome ${CHROME_USER_FLAGS} "${@}"