name: QA

on: [ merge_group, push, pull_request ]

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: codeberg-tiny
    container: archlinux:latest
    steps:
      - name: Create resolv.conf
        run: |
          set -ex
          echo 'nameserver 8.8.8.8' >/etc/resolv.conf
          echo 'nameserver 8.8.4.4' >>/etc/resolv.conf

      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S nodejs git typos

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Run spellchecker
        run: typos
