name: release
on:
  push:
    tags: ['v*']

  workflow_dispatch:
    inputs:
      head:
        description: "Git commit for release."
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.head || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [generic-amd64]

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{secrets.CI_TOKEN}}
          submodules: true
      - uses: actions/setup-go@v5
      
      - name: prepare vendor
        run: go mod tidy && go mod vendor

      - name: build-system-image
        run: make DEVICE=${{matrix.device}}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          file: '_cache/${{matrix.device}}/images/disk.img'
          asset_name: 'rlxos-${{ inputs.head || github.ref }}-${{matrix.device}}.img'
          tag: ${{ inputs.head || github.ref }}
          overwrite: true
          body: ${{ github.event.head_commit.message }}


