name: Build And Release
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

env:
  BST: bst --colors --builders 1

jobs:
  generate-cache:
    name: Generate Cache
    runs-on: self-hosted
    timeout-minutes: 46000
    steps:
      - uses: actions/checkout@v1
      - name: Build System Repository
        run: ${BST} -o variant experimental build system/repo.bst

  checkout-experimental:
    name: Checkout Experimental
    runs-on: self-hosted
    timeout-minutes: 46000
    needs: generate-cache
    environment: EXPERIMENTAL

    env:
      OSTREE_REPO: ${{ secrets.OSTREE_REPO }}
      OSTREE_GPG: ${{ secrets.OSTREE_GPG }}

    steps:
      - uses: actions/checkout@v1
      
      - name: Build Installer ISO
        run: ${BST} -o variant experimental build installer/image.bst
        
      - name: Checkout Image
        run: ${BST} -o variant experimental artifact checkout installer/image.bst --directory ${{ secrets.DAILY_DIR }} --force

      - name: Generate Changelog
        run: echo "${{ github.event.head_commit.message }}" > commit_body

      - name: Update ostree
        run: VARIANT="experimental" REF="system/repo.bst" make update-ostree

  release:
    name: Release
    runs-on: self-hosted
    needs: checkout-experimental
    environment: RELEASE
    if: github.ref == 'refs/heads/stable'
    strategy:
      matrix:
        variant:
          - desktop
          - workstation
    env:
      RELEASE_DIR: "${{ secrets.SERVER_REPO_PATH }}/releases/stable/"
      OSTREE_REPO: ${{ secrets.OSTREE_REPO }}
      OSTREE_GPG: ${{ secrets.OSTREE_GPG }}
    steps:
      - uses: actions/checkout@v1
      - name: BUILD
        run: ${BST} -o variant ${{matrix.variant}} build installer/image.bst
      - name: Checkout Image
        run: ${BST} -o variant ${{matrix.variant}} artifact checkout installer/image.bst --directory $RELEASE_DIR --force
      
      - name: Generate Changelog
        run: echo "${{ github.event.head_commit.message }}" > commit_body
      
      - name: Update ostree
        run: VARIANT="${{matrix.variant}}" REF="system/repo.bst" make update-ostree