name: Build and Release
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/update-docs.yml"
      - "mkdocs.yml"

env:
  NO_PROGRESS: 1
  SERVER_REPO_PATH: ${{secrets.SERVER_REPO_PATH}}
  SERVER_REPO_URL: ${{secrets.SERVER_REPO_URL}}
  CACHE_PATH: ${{secrets.SERVER_REPO_PATH}}
  VERSION: ${{ github.run_number }}
  SOURCEFORGE_PREFIX: ${{secrets.SOURCEFORGE_PREFIX}}
  CHANNEL: ${{ endsWith(github.ref, 'stable') && 'stable' || (endsWith(github.ref, 'preview') && 'preview' || 'unstable') }}
  APPMARKET_PATH: ${{secrets.APPMARKET_PATH}}
  SIGN_KEYS_PATH: ${{secrets.SIGN_KEYS_PATH}}

jobs:
  build:
    name: Build Collection
    runs-on: self-hosted
    timeout-minutes: 47000

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Add sign keys
        run: rm -rf files/sign-keys && cp -r ${SIGN_KEYS_PATH} files/sign-keys

      - name: Build system packages
        run: make ELEMENT=system/deps.yml

      - name: Write changelog
        run: echo "${{ github.event.head_commit.message }}" > ChangeLog

      - name: Generate metadata
        run: make metadata

      - name: Build Installer ISO
        run: make ELEMENT=installer/image.yml

  update-installer-iso:
    name: Update Installer ISO
    runs-on: self-hosted
    timeout-minutes: 47000
    needs: [ build ]

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Update installer ISO
        run: |-
          make checkout ELEMENT=installer/image.yml DESTDIR=${SERVER_REPO_PATH}/releases/${CHANNEL}/
          (cd ${SERVER_REPO_PATH}/releases/${CHANNEL}/; zsyncmake -b 2048 -C -u ${SERVER_REPO_URL}/releases/${CHANNEL}/rlxos-${CHANNEL}-installer.iso rlxos-${CHANNEL}-installer.iso)

      - name: Upload to sourceforge
        run: scp -pr ${SERVER_REPO_PATH}/releases/${CHANNEL}/ ${SOURCEFORGE_PREFIX}/
