name: Build and Release
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/update-docs.yml"
      - "mkdocs.yml"

env:
  CACHE_PATH: ${{ secrets.CACHE_PATH }}
  VERSION: ${{ github.run_number }}
  BRANCH: ${{ endsWith(github.ref, 'stable') && 'stable' || (endsWith(github.ref, 'preview') && 'preview' || 'unstable') }}

jobs:
  build:
    name: Build Collection
    runs-on: self-hosted
    timeout-minutes: 47000
    strategy:
      matrix:
        board:
          - x86_64-bios

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true
      - name: Build system packages
        run: make CACHE_PATH=$CACHE_PATH BOARD_NAME=${{matrix.board}}

      - name: Compress Image
        run: zstd -19 ${{env.CACHE_PATH}}/${{matrix.board}}/images/disk.img -o disk.img.zst

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: disk.img.zst
          asset_name: rlxos-${{matrix.board}}.img.zst
          tag: ${{env.BRANCH}}
          overwrite: true
          body: ${{ github.event.head_commit.message }}
