name: Update extension
on:
  push:
    paths:
      - 'elements/extensions/**'
      - .github/workflow/update-extensions.yml

env:
  BST: bst --colors --builders 1

jobs:
  update-extension:
    name: Updating extension
    runs-on: self-hosted
    timeout-minutes: 46000
    environment: EXPERIMENTAL
    env:
      OSTREE_REPO: ${{ secrets.OSTREE_REPO }}
      OSTREE_GPG: ${{ secrets.OSTREE_GPG }}
    steps:
      - uses: actions/checkout@v1
      - uses: jitterbit/get-changed-files@v1
        id: changes
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update extensions
        run: |
          VARIANT=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          ARCH=$(uname -m)
          for i in ${{ steps.changes.outputs.all }} ; do
            if [[ $i == "elements/extensions/*/repo.bst" ]] ; then
              i=$(echo $i | cut -d '/' -f2-)
              id=$(echo $i | cut -d '/' -f2)
              echo "=> generating extension ${id}"
              ${BST} -o variant ${VARIANT} build ${i}
              
              echo "=> commiting release ${VARIANT} ${REF}"
              VARIANT=${VARIANT} REF=${i} OSTREE_BRANCH=${ARCH}/${VARIANT}/extension/${id} make update-ostree
            fi
          done