name: Update Docs
on:
  push:
    branches:
      - stable

jobs:
  update-docs:
    name: Update Docs
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Build Documentation
        run: mkdocs build -d ${{secrets.DOCS_DIR}}